routes/web.php
<?php

use App\Http\Controllers\MasterDasaWismaController;
use App\Http\Controllers\PendatangController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FamilyController;
use App\Http\Controllers\CardFamilyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InhabitantController;
use App\Http\Controllers\ActivityController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// URL::forceScheme('https');
Route::get('/', function () {
    return view('auth.login');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', HomeController::class)->name('dashboard');

    Route::resource('families', FamilyController::class);

    Route::get('download/families', [FamilyController::class, 'download'])->name('families.download');
    Route::get('download/inhabitant', [InhabitantController::class, 'download'])->name('inhabitant.download');
    Route::get('download/pendatang', [PendatangController::class, 'download'])->name('pendatang.download');

    Route::get('families/{family}/cardfamily/create', [CardFamilyController::class, 'create'])->name('cardfamily.create');
    Route::post('families/{family}/cardfamily', [CardFamilyController::class, 'store'])->name('cardfamily.store');
    Route::get('families/{family}/cardfamily/{cardfamily}/edit', [CardFamilyController::class, 'edit'])->name('cardfamily.edit');
    Route::put('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'update'])->name('cardfamily.update');
    Route::delete('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'destroy'])->name('cardfamily.destroy');
    Route::get('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'show'])->name('cardfamily.show');

    Route::resource('inhabitants', InhabitantController::class);

    Route::get('inhabitants/{inhabitant}/activity/create', [ActivityController::class, 'create'])->name('activity.create');
    Route::post('inhabitants/{inhabitant}/activity', [ActivityController::class, 'store'])->name('activity.store');
    Route::get('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'show'])->name('activity.show');
    Route::get('inhabitants/{inhabitant}/activity/{activity}/edit', [ActivityController::class, 'edit'])->name('activity.edit');
    Route::put('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'update'])->name('activity.update');
    Route::delete('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'destroy'])->name('activity.destroy');

    Route::resource('masterdasawisma', MasterDasaWismaController::class);

    Route::resource('pendatang', PendatangController::class);
    // Route::get('pendatang/{pendatang}', PendatangController::class, 'detail')->name('pendatang.detail');

    // Route::get('/pendatang', PendatangController::class)->name('pendatang');
    Route::get('pendatang/create', [PendatangController::class, 'create'])->name('pendatang.create');
    Route::post('pendatang/store', [PendatangController::class, 'store'])->name('pendatang.store');
    Route::get('pendatang/edit/{pendatang}', [PendatangController::class, 'edit'])->name('pendatang.edit');
    Route::put('pendatang/update/{pendatang}', [PendatangController::class, 'update'])->name('pendatang.update');
});

app/Models/Family.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Family extends Model
{
    use HasFactory;

    protected $table = 'families';

    public function card()
    {
        return $this->hasOne(CardFamily::class);
    }

}

app/Http/Controllers/FamilyController.php
<?php

namespace App\Http\Controllers;

use App\Models\DownloadFamily;
use App\Models\Family;
use App\Models\CardFamily;
use App\Models\Inhabitant;
use App\Models\MasterDasaWisma;
use Illuminate\Http\Request;
// use Maatwebsite\Excel\Facades\Excel;
use RealRashid\SweetAlert\Facades\Alert;

class FamilyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $families = Family::all();
        $lk = Family::sum('jml_lk');
        $pr = Family::sum('jml_pr');
        return view('families.index', compact('families', 'lk', 'pr'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $dasawisma = MasterDasaWisma::orderBy('id', 'desc')->get();
        
        return view('families.create', compact('dasawisma'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Family $family)
    {
        $validation = $request->validate([
            'desa' => 'required',
            'rt' => 'required',
            'rw' => 'required',
            'dusun' => 'required',
            'kel' => 'required',
            // 'kep' => 'required',
            // 'kab' => 'required',
            // 'prov' => 'required',
            'nama_kk' => 'required',
            'ttl_anggota' => 'required',
            'jml_lk' => 'required',
            'jml_pr' => 'required',
            'jml_kk' => 'required',
            'jml_balita' => 'required',
            'jml_anak' => 'required',
            'jml_pus' => 'required',
            'jml_wus' => 'required',
            'jml_buta' => 'required',
            'jml_bumil' => 'required',
            'jml_busu' => 'required',
            'jml_lansia' => 'required',
            'makanan_pokok' => 'required',
            'jamban' => 'required',
            'sumber_air' => 'required',
            'pembuangan_sampah' => 'required',
            'pembuangan_air_limbah' => 'required',
            'stiker_p4k' => 'required',
            'kriteria_rumah' => 'required',
            'up2k' => 'required',
            'kukl' => 'required',
        ]);

        $family = new Family();
        $family->desa = $request->desa;
        $family->rt = $request->rt;
        $family->rw = $request->rw;
        $family->dusun = $request->dusun;
        $family->kel = $request->kel;
        $family->kep = ($request->kep) ?: "Ringinharjo";
        $family->kab = ($request->kab) ?: "Bantul";
        $family->prov = ($request->prov) ?: "Di Yogyakarta" ;
        $family->nama_kk = $request->nama_kk;
        $family->ttl_anggota = $request->ttl_anggota;
        $family->jml_lk = $request->jml_lk;
        $family->jml_pr = $request->jml_pr;
        $family->jml_kk = $request->jml_kk;
        $family->jml_balita = $request->jml_balita;
        $family->jml_anak = $request->jml_anak;
        $family->jml_pus = $request->jml_pus;
        $family->jml_wus = $request->jml_wus;
        $family->jml_buta = $request->jml_buta;
        $family->jml_bumil = $request->jml_bumil;
        $family->jml_busu = $request->jml_busu;
        $family->jml_lansia = $request->jml_lansia;
        $family->makanan_pokok = $request->makanan_pokok;
        $family->jamban = $request->jamban;
        $family->sumber_air = $request->sumber_air;
        $family->pembuangan_sampah = $request->pembuangan_sampah;
        $family->pembuangan_air_limbah = $request->pembuangan_air_limbah;
        $family->stiker_p4k = $request->stiker_p4k;
        $family->kriteria_rumah = $request->kriteria_rumah;
        $family->up2k = $request->up2k;
        $family->kukl = $request->kukl;
        $family->save();

        $warga = Inhabitant::find($request->id_kk);
        $cardfamily = new CardFamily();
        $cardfamily->family_id = $family->id;
        $cardfamily->no_reg = $warga->no_reg;
        $cardfamily->nik = $warga->nik;
        $cardfamily->nama_anggota_keluarga = $request->nama_kk;
        $cardfamily->status_dlm_keluarga = $warga->status_dlm_keluarga;
        $cardfamily->status_dlm_perkawinan = $warga->status_kawin;
        $cardfamily->jenis_kelamin = $warga->jenis_kelamin;
        $cardfamily->lahir_umur = $warga->tanggal_lahir;
        $cardfamily->pendidikan = $warga->pendidikan;
        $cardfamily->pekerjaan = $warga->pekerjaan;
        $cardfamily->save();

        return redirect()->route('families.index')->with('toast_success', 'Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $family = Family::find($id);
        $cardfamily = CardFamily::where('family_id', $id)->get();
        return view('families.show', compact('family', 'cardfamily'));
    }

    public function download()
    {
        return (new DownloadFamily)->download('family.xlsx');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $family = Family::find($id);
        return view('families.edit', compact('family'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'desa' => 'required',
            'rt' => 'required',
            'rw' => 'required',
            'dusun' => 'required',
            'kel' => 'required',
            'kep' => 'required',
            'kab' => 'required',
            'prov' => 'required',
            'nama_kk' => 'required',
            'ttl_anggota' => 'required',
            'jml_lk' => 'required',
            'jml_pr' => 'required',
            'jml_kk' => 'required',
            'jml_balita' => 'required',
            'jml_anak' => 'required',
            'jml_pus' => 'required',
            'jml_wus' => 'required',
            'jml_buta' => 'required',
            'jml_bumil' => 'required',
            'jml_busu' => 'required',
            'jml_lansia' => 'required',
            'makanan_pokok' => 'required',
            'jamban' => 'required',
            'sumber_air' => 'required',
            'pembuangan_sampah' => 'required',
            'pembuangan_air_limbah' => 'required',
            'stiker_p4k' => 'required',
            'kriteria_rumah' => 'required',
            'up2k' => 'required',
            'kukl' => 'required',
        ]);

        $family = Family::find($id);
        $family->desa = $request->desa;
        $family->rt = $request->rt;
        $family->rw = $request->rw;
        $family->dusun = $request->dusun;
        $family->kel = $request->kel;
        $family->kep = $request->kep;
        $family->kab = $request->kab;
        $family->prov = $request->prov;
        $family->nama_kk = $request->nama_kk;
        $family->ttl_anggota = $request->ttl_anggota;
        $family->jml_lk = $request->jml_lk;
        $family->jml_pr = $request->jml_pr;
        $family->jml_kk = $request->jml_kk;
        $family->jml_balita = $request->jml_balita;
        $family->jml_anak = $request->jml_anak;
        $family->jml_pus = $request->jml_pus;
        $family->jml_wus = $request->jml_wus;
        $family->jml_buta = $request->jml_buta;
        $family->jml_bumil = $request->jml_bumil;
        $family->jml_busu = $request->jml_busu;
        $family->jml_lansia = $request->jml_lansia;
        $family->makanan_pokok = $request->makanan_pokok;
        $family->jamban = $request->jamban;
        $family->sumber_air = $request->sumber_air;
        $family->pembuangan_sampah = $request->pembuangan_sampah;
        $family->pembuangan_air_limbah = $request->pembuangan_air_limbah;
        $family->stiker_p4k = $request->stiker_p4k;
        $family->kriteria_rumah = $request->kriteria_rumah;
        $family->up2k = $request->up2k;
        $family->kukl = $request->kukl;
        $family->save();

        return redirect()->route('families.index')
            ->with('toast_success', 'Data berhasil diubah');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $family = Family::find($id);
        $family->delete();

        return redirect()->route('families.index')
            ->with('toast_success', 'Data berhasil dihapus');
    }
}

resources/views/families/create-anggota-keluarga.blade.php
<div class="card">
    <button type="button" class="card-header" data-bs-toggle="collapse" href="#collapseAnggotaKeluarga" role="button" aria-expanded="false" aria-controls="collapseAnggotaKeluarga">
        <h4 class="fw-bolder">Anggota Keluarga</h4>
    </button>
    <div class="collapse card-body show" id="collapseAnggotaKeluarga">
        
        <div class="row">
        
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="nama_kk">Nama Kepala Rumah Tangga</label>
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="text" name="search_nik" id="search_nik"
                            class="form-control round"
                            placeholder="Masukkan Nik Nama Kepala Rumah Tanggga">
                        </div>
                        <div class="col-lg-5">
                            <button type="button" class="btn btn-info btn-sm" id="search_by_nik">Cari</button>
                        </div>
                    </div>

                    @error('nama_kk')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div id="show_nama_kk" class="col-lg-12">
                <div class="form-group">
                    <input type="text" name="nama_kk_show" id="nama_kk_show" class="form-control round" value="" disabled>
                    <input type="hidden" name="nama_kk" id="nama_kk" class="form-control round" value="">
                    <input type="hidden" name="id_kk" id="id_kk" class="form-control round" value="">
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="ttl_anggota">Jumlah Anggota Keluarga</label>
                    <input type="number" name="ttl_anggota" id="ttl_anggota"
                        class="form-control round" placeholder="Jumlah Anggota Keluarga">

                    @error('ttl_anggota')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_lk">Laki-laki</label>
                    <input type="number" name="jml_lk" id="jml_lk"
                        class="form-control round" placeholder="Laki-laki">

                    @error('jml_lk')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_pr">Perempuan</label>
                    <input type="number" name="jml_pr" id="jml_pr"
                        class="form-control round" placeholder="Perempuan">

                    @error('jml_pr')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_kk">Jumlah KK</label>
                    <input type="number" name="jml_kk" id="jml_kk"
                        class="form-control round" placeholder="Jumlah KK">

                    @error('jml_kk')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="balita">Balita</label>
                    <input type="number" name="jml_balita" id="balita"
                        class="form-control round" placeholder="Balita">

                    @error('jml_balita')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="anak">Anak</label>
                    <input type="number" name="jml_anak" id="anak"
                        class="form-control round" placeholder="Anak">

                    @error('jml_anak')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="pus">PUS</label>
                    <input type="number" name="jml_pus" id="pus"
                        class="form-control round" placeholder="PUS">

                    @error('jml_pus')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="wus">WUS</label>
                    <input type="number" name="jml_wus" id="wus"
                        class="form-control round" placeholder="WUS">

                    @error('jml_wus')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="buta">Buta</label>
                    <input type="number" name="jml_buta" id="buta"
                        class="form-control round" placeholder="Buta">

                    @error('jml_buta')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_bumil">Ibu Hamil</label>
                    <input type="number" name="jml_bumil" id="jml_bumil"
                        class="form-control round" placeholder="Ibu Hamil">

                    @error('jml_bumil')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_busu">Ibu Menyusui</label>
                    <input type="number" name="jml_busu" id="jml_busu"
                        class="form-control round" placeholder="Ibu Menyusui">

                    @error('jml_busu')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="jml_lansia">Lansia</label>
                    <input type="number" name="jml_lansia" id="jml_lansia"
                        class="form-control round" placeholder="Lansia">

                    @error('jml_lansia')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>

        </div>

    </div>
</div>

resources/views/families/create.blade.php
@section('title', 'Tambah Data Keluarga')
@extends('layouts.voler')
@section('content')
    <div id="main">
        <x-navbar></x-navbar>

        <div class="main-content container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h4>@yield('title')</h4>
                        <!-- <p class="text-subtitle text-muted">We use 'simple-datatables' made by @fiduswriter. You can check
                            the full documentation <a href="https://github.com/fiduswriter/Simple-DataTables/wiki">here</a>.
                        </p> -->
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class='breadcrumb-header'>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('families.index') }}">Data Keluarga</a></li>
                                <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <section id="basic-input-groups">
                <div class="row">
                    <div class="col-12">
                        <form action="{{ route('families.store') }}" method="POST">
                            @csrf
                            <div class="card">
                                <div class="card-content">
                                    <div class="card-body">
                                        @include('families.create-lokasi')
                                        @include('families.create-anggota-keluarga')
                                        @include('families.create-keadaan-rumah')
                                        <button type="submit" class="btn btn-primary">Simpan</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
        <x-footer></x-footer>
    </div>

<script>
    // $('#show_nama_kk').css('display', 'none');
    $('#search_by_nik').click(() => {
        $('#search_by_nik').prop('disabled', true)
        $('#search_by_nik').html('')
        html = `<div class="spinner-grow spinner-grow-sm" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>`
        $('#search_by_nik').html(html)

        $.ajax({
            method: 'GET',
            url: '{{ url("api/warga/by_nik") }}',
            data: { nik: $('#search_nik').val() }
        })
        .done(function(data) {
            $('#id_kk').val(data.data.id)
            $('#nama_kk').val(data.data.nama)
            $('#nama_kk_show').val(data.data.nama)
            $('#search_by_nik').prop('disabled', '')
            $('#search_by_nik').html('Cari')
            // $('#show_nama_kk').css('display', 'block');
        })
    })
</script>
@endsection

resources/views/families/index.blade.php
@section('title', 'Data Keluarga')
@extends('layouts.voler')
@section('content')
    <div id="main">
        <x-navbar></x-navbar>

        <div class="main-content container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>@yield('title')</h3>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class='breadcrumb-header'>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <section class="section">
                    <div class="row mb-2">
                        <div class="col-12 col-md-6">
                            <div class="card card-statistic">
                                <div class="card-body p-0">
                                    <div class="d-flex flex-column">
                                        <div class='px-3 py-3 d-flex justify-content-between'>
                                            <h4 class='card-title'>Total Laki-laki</h4>
                                            <div class="card-right d-flex align-items-center">
                                                <p>{{ $lk }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="card card-statistic">
                                <div class="card-body p-0">
                                    <div class="d-flex flex-column">
                                        <div class='px-3 py-3 d-flex justify-content-between'>
                                            <h4 class='card-title'>Total Perempuan</h4>
                                            <div class="card-right d-flex align-items-center">
                                                <p>{{ $pr }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            </section>
        </div>
        <section class="section">
            <div class="card">
                <div class="card-header row">
                    <div class="col-lg-2">
                        <a href="{{ route('families.create') }}" class="btn icon icon-left btn-primary">
                            <i data-feather="plus"></i>
                            <span>Tambah Data</span>
                        </a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{{ route('families.download') }}" class="btn icon btn-success">
                            <i data-feather="download"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class='table' id="table1">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Dasa Wisma</th>
                                <th>RT</th>
                                <th>RW</th>
                                <th>Nama Kepala Rumah Tangga</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($families as $family)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $family->desa }}</td>
                                    <td>{{ $family->rt }}</td>
                                    <td>{{ $family->rw }}</td>
                                    <td>{{ $family->nama_kk }}</td>
                                    <td>
                                        <!-- <a href="{{ route('cardfamily.create', $family->id) }}"
                                            class="btn icon icon-left btn-success btn-sm">
                                            <i data-feather="plus"></i>
                                            <span>KK</span>
                                        </a> -->
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <a href="{{ route('cardfamily.show', [$family->id, $family->id]) }}"
                                                    class="btn icon icon-left btn-primary btn-sm">
                                                    <i data-feather="eye"></i>
                                                    <!-- <span>KK</span> -->
                                                </a>
                                            </div>
                                            <div class="col-lg-3">
                                                <a href="{{ route('families.show', $family->id) }}"
                                                    class="btn icon btn-info btn-sm">
                                                    <i data-feather="printer"></i>
                                                </a>
                                            </div>
                                            <div class="col-lg-3">
                                                <a href="{{ route('families.edit', $family->id) }}"
                                                    class="btn icon icon-left btn-warning btn-sm">
                                                    <i data-feather="edit"></i>
                                                </a>
                                            </div>
                                            <div class="col-lg-3">
                                                <form action="{{ route('families.destroy', $family->id) }}" method="POST"
                                                class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn icon icon-left btn-danger btn-sm"
                                                        onclick="return confirm('Yakin ingin menghapus data?')">
                                                        <i data-feather="trash"></i>
                                                    </button>
                                                </form>
                                            </div>
                                            
                                        </div>
                                    </td>
                                </tr>
                            @endforeach

                            @if ($families->count() == 0)
                                <tr>
                                    <td colspan="4" class="text-center">Data Kosong</td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>

        </section>
    </div>
    <x-footer></x-footer>
    </div>
@endsection