routes/web.php
<?php

use App\Http\Controllers\MasterDasaWismaController;
use App\Http\Controllers\PendatangController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FamilyController;
use App\Http\Controllers\CardFamilyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InhabitantController;
use App\Http\Controllers\ActivityController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// URL::forceScheme('https');
Route::get('/', function () {
    return view('auth.login');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', HomeController::class)->name('dashboard');

    Route::resource('families', FamilyController::class);

    Route::get('download/families', [FamilyController::class, 'download'])->name('families.download');
    Route::get('download/inhabitant', [InhabitantController::class, 'download'])->name('inhabitant.download');
    Route::get('download/pendatang', [PendatangController::class, 'download'])->name('pendatang.download');

    Route::get('families/{family}/cardfamily/create', [CardFamilyController::class, 'create'])->name('cardfamily.create');
    Route::post('families/{family}/cardfamily', [CardFamilyController::class, 'store'])->name('cardfamily.store');
    Route::get('families/{family}/cardfamily/{cardfamily}/edit', [CardFamilyController::class, 'edit'])->name('cardfamily.edit');
    Route::put('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'update'])->name('cardfamily.update');
    Route::delete('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'destroy'])->name('cardfamily.destroy');
    Route::get('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'show'])->name('cardfamily.show');

    Route::resource('inhabitants', InhabitantController::class);

    Route::get('inhabitants/{inhabitant}/activity/create', [ActivityController::class, 'create'])->name('activity.create');
    Route::post('inhabitants/{inhabitant}/activity', [ActivityController::class, 'store'])->name('activity.store');
    Route::get('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'show'])->name('activity.show');
    Route::get('inhabitants/{inhabitant}/activity/{activity}/edit', [ActivityController::class, 'edit'])->name('activity.edit');
    Route::put('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'update'])->name('activity.update');
    Route::delete('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'destroy'])->name('activity.destroy');

    Route::resource('masterdasawisma', MasterDasaWismaController::class);

    Route::resource('pendatang', PendatangController::class);
    // Route::get('pendatang/{pendatang}', PendatangController::class, 'detail')->name('pendatang.detail');

    // Route::get('/pendatang', PendatangController::class)->name('pendatang');
    Route::get('pendatang/create', [PendatangController::class, 'create'])->name('pendatang.create');
    Route::post('pendatang/store', [PendatangController::class, 'store'])->name('pendatang.store');
    Route::get('pendatang/edit/{pendatang}', [PendatangController::class, 'edit'])->name('pendatang.edit');
    Route::put('pendatang/update/{pendatang}', [PendatangController::class, 'update'])->name('pendatang.update');
});

app/Models/MasterDasaWisma.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MasterDasaWisma extends Model
{
    use HasFactory;

    protected $table = "m_dasawisma";

    public function masterdasawisma() 
    {
        return $this->belongsTo(MasterDasaWisma::class);
    }

}

app/Http/Controllers/MasterDasaWismaController.php
<?php

namespace App\Http\Controllers;

use App\Models\MasterDasaWisma;
use Illuminate\Http\Request;

class MasterDasaWismaController extends Controller
{
    
    public function index() {

        $dasawisma = MasterDasaWisma::orderBy('id', 'desc')->get();

        return view('masterdasawisma.index', compact('dasawisma'));

    }

    public function store(Request $request, MasterDasaWisma $masterDasaWisma) {

        $request->validate(['desa' => 'required']);

        $masterDasaWisma = new MasterDasaWisma();
        $masterDasaWisma->name = $request->desa;
        $masterDasaWisma->save();

        return redirect()->route('masterdasawisma.index')->with('toast_success', 'Data berhasil ditambahkan');

    }

    public function update(Request $request, $id) {

        $request->validate(['desa' => 'required']);

        if (empty($request->desa)) {
            return redirect()->route('masterdasawisma.index')->with('toast_error', 'Data gagal diupdate');
        } else {
            $masterDasaWisma = MasterDasaWisma::find($id);
            $masterDasaWisma->name = $request->desa;
            $masterDasaWisma->save();

            return redirect()->route('masterdasawisma.index')->with('toast_success', 'Data berhasil diupdate');
        }

    }

    public function destroy($id)
    {
        $masterDasaWisma = MasterDasaWisma::find($id);
        $masterDasaWisma->delete();

        return redirect()->route('masterdasawisma.index')->with('toast_success', 'Data berhasil dihapus');
    }
    
}

resources/views/masterdasawisma/index.blade.php
@section('title', 'Master Dasa Wisma')
@extends('layouts.voler')
@section('content')
    <div id="main">
        <x-navbar></x-navbar>

        <div class="main-content container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>@yield('title')</h3>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class='breadcrumb-header'>
                            <ol class="breadcrumb">
                                <!-- <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li> -->
                                <!-- <li class="breadcrumb-item active" aria-current="page">@yield('title')</li> -->
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <section class="section">
                <div class="card">
                    <div class="card-header">
                        <button type="button" class="btn icon btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                            <i data-feather="plus"></i>
                        </button>
                    </div>
                    <div class="card-body">
                        <table class='table table-hover table-striped' id="table1">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Nama</th>
                                    <th>Tanggal Buat</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!empty($dasawisma))
                                    @foreach ($dasawisma as $no => $row)
                                        <tr>
                                            <td>{{ $no+1 }}</td>
                                            <td>{{ $row->name }}</td>
                                            <td>{{ $row->created_at }}</td>
                                            <td>
                                                <button type="button" class="btn icon btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editData{{ $row->id }}">
                                                    <i data-feather="edit"></i>
                                                </button>
                                                <button type="button" class="btn icon btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#hapusData{{ $row->id }}">
                                                    <i data-feather="trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach

                                    @if ($dasawisma->count() == 0)
                                        <tr>
                                            <td colspan="4" class="text-center">Data Kosong</td>
                                        </tr>
                                    @endif
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>

            </section>
        @include('masterdasawisma.modal')
        @include('masterdasawisma.modal-edit')
        </div>
        <script>
            // $('#tableDasaWisma').dataTable( {
            //         "columnDefs": [ {
            //         "targets": 'no-sort',
            //         "orderable": false,
            //     } ]
            // } );
        </script>
        <x-footer></x-footer>
    </div>
@endsection

resources/views/masterdasawisma/modal-edit.blade.php
@if (!empty($dasawisma))
@foreach ($dasawisma as $no => $row)

<div class="modal fade" id="editData{{ $row->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Edit data dasa wisma</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('masterdasawisma.update', $row->id) }}" method="POST">
            @method('PUT')
            @csrf
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="desa">Nama Dasa Wisma</label>
                        <input type="text" name="desa" id="editDasaWisma{{ $row->id }}" onChange="checkInputEdit({{ $row->id }})" value="{{ $row->name }}" class="form-control round" placeholder="Desa Wisma">
                        <div id="textErrorEdit{{ $row->id }}" class="text-danger"></div>
                    </div>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" id="tombolEdit{{ $row->id }}" class="btn btn-primary">Edit</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="hapusData{{ $row->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
      </div>
      <div class="modal-body">
        <form action="{{ route('masterdasawisma.destroy', $row->id) }}" method="POST">
            @method('delete')
            @csrf
            <div class="row">
                <div class="col-lg-12 text-center">
                   <h4>Yakin menghapus data ini ?</h4>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-info">Ya</button>
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Tidak</button>
        </form>
      </div>
    </div>
  </div>
</div>

@endforeach

<script>
    function checkInputEdit(id) {
        var name = $("#editDasaWisma"+id).val()
        if (name == "") {
            $("#textErrorEdit"+id).html("Nama dasa wisma wajib di isi")
            $("#tombolEdit"+id).prop("disabled", true)
        } else {
            $("#textErrorEdit"+id).html("")
            $("#tombolEdit"+id).prop("disabled", false)
        }
    }
</script>
@endif

resources/views/masterdasawisma/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Tambah data dasa wisma</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('masterdasawisma.store') }}" method="POST">
            @csrf
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="desa">Desa Wisma</label>
                        <input type="text" name="desa" id="desa" class="form-control round" onChange="checkInput()" placeholder="Desa Wisma">
                        @error('desa')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" id="tombolSimpan" class="btn btn-primary" disabled>Simpan</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
    function checkInput() {
        var desa = $("#desa").val();
        if (desa) {
            $("#tombolSimpan").prop("disabled", false);
        }
    }
</script>