routes/web.php
<?php

use App\Http\Controllers\MasterDasaWismaController;
use App\Http\Controllers\PendatangController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FamilyController;
use App\Http\Controllers\CardFamilyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InhabitantController;
use App\Http\Controllers\ActivityController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// URL::forceScheme('https');
Route::get('/', function () {
    return view('auth.login');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', HomeController::class)->name('dashboard');

    Route::resource('families', FamilyController::class);

    Route::get('download/families', [FamilyController::class, 'download'])->name('families.download');
    Route::get('download/inhabitant', [InhabitantController::class, 'download'])->name('inhabitant.download');
    Route::get('download/pendatang', [PendatangController::class, 'download'])->name('pendatang.download');

    Route::get('families/{family}/cardfamily/create', [CardFamilyController::class, 'create'])->name('cardfamily.create');
    Route::post('families/{family}/cardfamily', [CardFamilyController::class, 'store'])->name('cardfamily.store');
    Route::get('families/{family}/cardfamily/{cardfamily}/edit', [CardFamilyController::class, 'edit'])->name('cardfamily.edit');
    Route::put('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'update'])->name('cardfamily.update');
    Route::delete('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'destroy'])->name('cardfamily.destroy');
    Route::get('families/{family}/cardfamily/{cardfamily}', [CardFamilyController::class, 'show'])->name('cardfamily.show');

    Route::resource('inhabitants', InhabitantController::class);

    Route::get('inhabitants/{inhabitant}/activity/create', [ActivityController::class, 'create'])->name('activity.create');
    Route::post('inhabitants/{inhabitant}/activity', [ActivityController::class, 'store'])->name('activity.store');
    Route::get('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'show'])->name('activity.show');
    Route::get('inhabitants/{inhabitant}/activity/{activity}/edit', [ActivityController::class, 'edit'])->name('activity.edit');
    Route::put('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'update'])->name('activity.update');
    Route::delete('inhabitants/{inhabitant}/activity/{activity}', [ActivityController::class, 'destroy'])->name('activity.destroy');

    Route::resource('masterdasawisma', MasterDasaWismaController::class);

    Route::resource('pendatang', PendatangController::class);
    // Route::get('pendatang/{pendatang}', PendatangController::class, 'detail')->name('pendatang.detail');

    // Route::get('/pendatang', PendatangController::class)->name('pendatang');
    Route::get('pendatang/create', [PendatangController::class, 'create'])->name('pendatang.create');
    Route::post('pendatang/store', [PendatangController::class, 'store'])->name('pendatang.store');
    Route::get('pendatang/edit/{pendatang}', [PendatangController::class, 'edit'])->name('pendatang.edit');
    Route::put('pendatang/update/{pendatang}', [PendatangController::class, 'update'])->name('pendatang.update');
});

app/Models/Inhabitant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inhabitant extends Model
{
    use HasFactory;

    protected $table = 'inhabitants';

    public function activities()
    {
        return $this->hasOne(Activity::class);
    }
}

app/Http/Controllers/InhabitantController.php
<?php

namespace App\Http\Controllers;

use App\Models\DownloadInhabitant;
use App\Models\MasterDasaWisma;
use Illuminate\Http\Request;
use App\Models\Inhabitant;
use App\Models\Activity;
use RealRashid\SweetAlert\Facades\Alert;

class InhabitantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $inhabitants = Inhabitant::all();
        return view('inhabitant.index', compact('inhabitants'));
    }

    public function download()
    {
        return (new DownloadInhabitant)->download('inhabitant.xlsx');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $dasawisma = MasterDasaWisma::orderBy('id', 'desc')->get();

        return view('inhabitant.create', compact('dasawisma'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Inhabitant $inhabitant)
    {
        $validation = $request->validate([
            'desa' => 'required',
            // 'nama_kk' => 'required',
            'no_reg' => 'required',
            'nik' => 'required',
            'nama' => 'required',
            'jabatan' => 'nullable',
            'jenis_kelamin' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'status_kawin' => 'required',
            'status_dlm_keluarga' => 'required',
            'agama' => 'required',
            'alamat' => 'required',
            'pendidikan' => 'required',
            'pekerjaan' => 'required',
            'akseptor_kb' => 'required',
            'posyandu' => 'required',
            'bina_keluarga_balita' => 'required',
            'paud' => 'required',
            'koperasi' => 'required',
        ]);

        $inhabitant = new Inhabitant();
        $inhabitant->desa = $request->desa;
        $inhabitant->nama_kk = $request->nama_kk;
        $inhabitant->no_reg = $request->no_reg;
        $inhabitant->nik = $request->nik;
        $inhabitant->nama = $request->nama;
        $inhabitant->jabatan = $request->jabatan;
        $inhabitant->jenis_kelamin = $request->jenis_kelamin;
        $inhabitant->tempat_lahir = $request->tempat_lahir;
        $inhabitant->tanggal_lahir = $request->tanggal_lahir;
        $inhabitant->status_kawin = $request->status_kawin;
        $inhabitant->status_dlm_keluarga = $request->status_dlm_keluarga;
        $inhabitant->agama = $request->agama;
        $inhabitant->alamat = $request->alamat;
        $inhabitant->pendidikan = $request->pendidikan;
        $inhabitant->pekerjaan = $request->pekerjaan;
        $inhabitant->akseptor_kb = $request->akseptor_kb;
        $inhabitant->posyandu = $request->posyandu;
        $inhabitant->bina_keluarga_balita = $request->bina_keluarga_balita;
        $inhabitant->paud = $request->paud;
        $inhabitant->koperasi = $request->koperasi;
        $inhabitant->save();

        return redirect()->route('inhabitants.index')->with('toast_success', 'Data Warga berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $inhabitants = Inhabitant::find($id);
        $activities = Activity::where('inhabitant_id', $id)->get();
        $dateofbirth = $inhabitants->tanggal_lahir;
        $age = date('Y') - date('Y', strtotime($dateofbirth));

        return view('inhabitant.show', compact('inhabitants', 'activities', 'age'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $inhabitant = Inhabitant::find($id);
        $dasa_wisma = MasterDasaWisma::query()->where('name', '!=', $inhabitant->desa)->get();

        return view('inhabitant.edit', compact('inhabitant','dasa_wisma'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'desa' => 'required',
            'nama_kk' => 'required',
            'no_reg' => 'required',
            'nik' => 'required',
            'nama' => 'required',
            'jabatan' => 'required',
            'jenis_kelamin' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'status_kawin' => 'required',
            'status_dlm_keluarga' => 'required',
            'agama' => 'required',
            'alamat' => 'required',
            'pendidikan' => 'required',
            'pekerjaan' => 'required',
            'akseptor_kb' => 'required',
            'posyandu' => 'required',
            'bina_keluarga_balita' => 'required',
            'paud' => 'required',
            'koperasi' => 'required',
        ]);

        $inhabitant = Inhabitant::find($id);
        $inhabitant->desa = $request->desa;
        $inhabitant->nama_kk = $request->nama_kk;
        $inhabitant->no_reg = $request->no_reg;
        $inhabitant->nik = $request->nik;
        $inhabitant->nama = $request->nama;
        $inhabitant->jabatan = $request->jabatan;
        $inhabitant->jenis_kelamin = $request->jenis_kelamin;
        $inhabitant->tempat_lahir = $request->tempat_lahir;
        $inhabitant->tanggal_lahir = $request->tanggal_lahir;
        $inhabitant->status_kawin = $request->status_kawin;
        $inhabitant->status_dlm_keluarga = $request->status_dlm_keluarga;
        $inhabitant->agama = $request->agama;
        $inhabitant->alamat = $request->alamat;
        $inhabitant->pendidikan = $request->pendidikan;
        $inhabitant->pekerjaan = $request->pekerjaan;
        $inhabitant->akseptor_kb = $request->akseptor_kb;
        $inhabitant->posyandu = $request->posyandu;
        $inhabitant->bina_keluarga_balita = $request->bina_keluarga_balita;
        $inhabitant->paud = $request->paud;
        $inhabitant->koperasi = $request->koperasi;
        $inhabitant->save();

        return redirect()->route('inhabitants.index')->with('toast_success', 'Data Warga berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $inhabitant = Inhabitant::find($id);
        $inhabitant->delete();

        return redirect()->route('inhabitants.index')->with('toast_success', 'Data Warga berhasil dihapus');
    }
}

resources/views/inhabitant/index.blade.php
@section('title', 'Data Warga')
@extends('layouts.voler')
@section('content')
    <div id="main">
        <x-navbar></x-navbar>

        <div class="main-content container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>@yield('title')</h3>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class='breadcrumb-header'>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <section class="section">
                <div class="card">
                    <div class="card-header row">
                        <div class="col-lg-2">
                            <a href="{{ route('inhabitants.create') }}" class="btn icon icon-left btn-primary">
                                <i data-feather="plus"></i>
                                <span>Tambah Data</span>
                            </a>
                        </div>
                        <div class="col-lg-3">
                            <a href="{{ url('download/inhabitant') }}" class="btn icon btn-success">
                                <i data-feather="download"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class='table' id="table1">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Dasawisma</th>
                                    <th>No. Registrasi</th>
                                    <th>Nama</th>
                                    <th>Jabatan</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($inhabitants as $inhabitant)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $inhabitant->desa }}</td>
                                        <td>{{ $inhabitant->no_reg }}</td>
                                        <td>{{ $inhabitant->nama }}</td>
                                        <td>{{ $inhabitant->jabatan }}</td>
                                        <td>
                                            <a href="{{ route('activity.create', $inhabitant->id) }}"
                                                class="btn icon btn-success btn-sm">
                                                <i data-feather="plus"></i>
                                                <span>Ac</span>
                                            </a>
                                            <a href="{{ route('activity.show', [$inhabitant->id, $inhabitant->id]) }}"
                                                class="btn icon btn-primary btn-sm">
                                                <i data-feather="eye"></i>
                                                <span>Ac</span>
                                            </a>
                                            <a href="{{ route('inhabitants.show', $inhabitant->id) }}"
                                                class="btn icon btn-info btn-sm">
                                                <i data-feather="eye"></i>
                                            </a>
                                            <a href="{{ route('inhabitants.edit', $inhabitant->id) }}"
                                                class="btn icon icon-left btn-warning btn-sm">
                                                <i data-feather="edit"></i>
                                            </a>
                                            <form action="{{ route('inhabitants.destroy', $inhabitant->id) }}"
                                                method="POST" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn icon icon-left btn-danger btn-sm"
                                                    onclick="return confirm('Yakin ingin menghapus data?')">
                                                    <i data-feather="trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                @if ($inhabitants->count() == 0)
                                    <tr>
                                        <td colspan="4" class="text-center">Data Kosong</td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>

            </section>
        </div>
        <x-footer></x-footer>
    </div>
@endsection

resources/views/inhabitant/show.blade.php
@section('title', 'Data Warga TP-PKK')
@extends('layouts.bt5')
@section('content')
    <div class="container mt-3">
        <center>
            <h5>Data Warga TP-PKK</h5>
        </center>

        <p class="mt-2 mb-0">Dasawisma : {{ $inhabitants->desa }}</p>
        <p class="mb-0">Nama Kepala Rumah Tangga : {{ $inhabitants->nama_kk }}</p>
        <ol>
            <li>
                <p class="mb-0">No. Registrasi : {{ $inhabitants->no_reg }}</p>
            </li>
            <li>
                <p class="mb-0">No. KTP/NIK : {{ $inhabitants->nik }}</p>
            </li>
            <li>
                <p class="mb-0">Nama : {{ $inhabitants->nama }}</p>
            </li>
            <li>
                <p class="mb-0">Jabatan : {{ $inhabitants->jabatan }}</p>
            </li>
            <li>
                <p class="mb-0">Jenis Kelamin : {{ $inhabitants->jenis_kelamin }}</p>
            </li>
            <li>
                <p class="mb-0">Tempat Lahir : {{ $inhabitants->tempat_lahir }}</p>
            </li>
            <li>
                <p class="mb-0">Tanggal Lahir : {{ $inhabitants->tanggal_lahir }} Umur : {{ $age }} Tahun</p>
            </li>
            <li>
                <p class="mb-0">Status Perkawinan : {{ $inhabitants->status_kawin }}</p>
            </li>
            <li>
                <p class="mb-0">Status Dalam Keluarga : {{ $inhabitants->status_dlm_keluarga }}</p>
            </li>
            <li>
                <p class="mb-0">Agama : {{ $inhabitants->agama }}</p>
            </li>
            <li>
                <p class="mb-0">Alamat : {{ $inhabitants->alamat }}</p>
            </li>
            <li>
                <p class="mb-0">Pendidikan : {{ $inhabitants->pendidikan }}</p>
            </li>
            <li>
                <p class="mb-0">Pekerjaan : {{ $inhabitants->pekerjaan }}</p>
            </li>
            <li>
                <p class="mb-0">Akseptor KB : {{ $inhabitants->akseptor_kb }}</p>
            </li>
            <li>
                <p class="mb-0">Aktif dalam kegiatan Posyandu : {{ $inhabitants->posyandu }}</p>
            </li>
            <li>
                <p class="mb-0">Mengikuti Program Bina Keluarga Balita : {{ $inhabitants->bina_keluarga_balita }}</p>
            </li>
            <li>
                <p class="mb-0">Mengikuti PAUD/Sejenis : {{ $inhabitants->paud }}</p>
            </li>
            <li>
                <p class="mb-0">Ikut dalam Kegiatan Koperasi : {{ $inhabitants->koperasi }}</p>
            </li>
        </ol>
        <center>
            <h5>Kegiatan Warga</h5>
        </center>
        <table class="table text-center table-bordered">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Kegiatan</th>
                    <th scope="col">Aktivitas Y/T</th>
                    <th scope="col">Keterangan (Jenis Kegiatan Yang Diikuti)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($activities as $activity)
                    <tr>
                        <td scope="row">{{ $loop->iteration }}</td>
                        <td>{{ $activity->nama_kegiatan }}</td>
                        <td>{{ $activity->status }}</td>
                        <td>{{ $activity->deskripsi }}</td>
                    </tr>
                @endforeach
            </tbody>
    </div>
@endsection